### PR TITLE
Add code copy button

### PR DESCRIPTION
**Pull request by ribice**
Adds a code copy button as explained [here](https://www.dannyguo.com/blog/how-to-add-copy-to-clipboard-buttons-to-code-blocks-in-hugo/).

Currently the button still doesn't show up, I'm investigating the reason.

### CODE REVIEW

**Comment by ribice** [comment]
@dguo I copied the new instructions from your blog post and it seems fine one, except for the styling.

image

**Comment by dguo** [comment]
Glad to hear it's working. Yeah, it's up to you how you want to style them in a way that fits the theme.

**Comment by ribice** [comment]
I was rather curious why it differs from yours while the css is the same.

**Comment by dguo** [comment]
That's odd. I pulled down the changes, and on the example site, they look like on my site. Though there seems to be more padding.

Screen Shot 2019-03-26 at 6 05 30 PM

**Pull request merged**
