### PR TITLE
Add Microsoft Clarity support

### PR DESCRIPTION
**Pull request by mateimicu**
Add support for [Microsoft Clarity](https://clarity.microsoft.com/)

### CODE REVIEW

**Comment by DanielRuf** [comment]
I'm not sure if it makes sense to add support for every single tracking service.

Clarity is also one of the services, that I don't know. Don't most companies load such scripts through Google Tag Manager? Never seen anyone using Clarity and not sure if this makes sense for the demo website and if there is so much usage or demand / interest, that it would be useful.

What issue does this PR resolve?

**Comment by DanielRuf** [comment]
Most users will probably extend the header template.

**Comment by mateimicu** [comment]
I do agree that adding support for every tool does not make sense; I followed the example already provided for the other Analitycs tools.

I am not sure how to modify the header template; You mean adding something like `customJS` like here https://github.com/ribice/kiss/blob/master/layouts/partials/header.html#L18 ? 

I could close this PR and open another one for that;

**Comment by DanielRuf** [comment]
Normally you would copy and modify the header partial or use something like the customcss setting.

If we add something for js, it should be one for head and one for body, if this makes sense.

**Pull request closed without merging**
