### PR TITLE
revert-pr-39

### PR DESCRIPTION
**Pull request by dinusuresh**
Revert PR#39 inorder to resolve issue #37

### CODE REVIEW

**Comment by ribice** [comment]
What's the issue you're facing? The one you linked seems to be resolved.

**Comment by dinusuresh** [comment]
The same issue as #37 . I believe that was a bug in hugo and it was fixed in the later versions. The pr #39 change now causes the same error as in #37 

Error with pr #39 
```
Building sites … ERROR 2019/05/08 00:46:26 Error while rendering "taxonomy" in "": html/template:theme/_default/list.html:1:12: no such template "index.html"
```

After reverting the pr #39 it works!

**Comment by olehermanse** [comment]
@dinusuresh can you check what version of hugo you are using?

**Comment by dinusuresh** [comment]
> @dinusuresh can you check what version of hugo you are using?

I apologize. It is the version problem on my end. I have wsl setup, and hugo is installed on both windows and wsl. I was referring to the latest hugo version on windows, while my hugo on wsl is @0.40.1. 

Upgrading to latest works flawlessly! Cheers :beers:

Thanks for pointing it out @olehermanse

**Pull request closed without merging**
