### PR TITLE
Sync with docs

### PR DESCRIPTION
**Pull request by jbrodriguez**
Docs mention 'image' in Single Page configuration

Code was referring to 'cover'

### CODE REVIEW

**Comment by ribice** [comment]
I'd rather replace it in the docs not to introduce any breaking changes. Can you please do that?

**Comment by jbrodriguez** [comment]
The thing is there's still a conflict, what you have right now is:

- 'cover' in https://github.com/ribice/kiss/blob/master/layouts/partials/social/twitter.html#L1
- 'image' in https://github.com/ribice/kiss/blob/master/layouts/partials/social/opengraph.html#L13
- 'image' in docs

How would like to handle it ?

**Comment by ribice** [comment]
I think opengraph covers Twitter as well?

https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started.html#opengraph

**Comment by jbrodriguez** [comment]
Yes, opengraph covers twitter.

But, as of now, you need to set both 'image' and 'cover' in the front matter:
- 'image' for the actual image url
- 'cover' to get the 'summary_large_image' twitter card type

I'm setting a cover: true tag in the front matter (as a workaround)

Ideally, it should work with only one tag (either 'image' or 'cover')

**Pull request merged**
