### PR TITLE
Add the ability to link static elements in the nav

### PR DESCRIPTION
**Pull request by mateimicu**
Basically you can define something like this 
```
[[params.static]]                                                                                                                                                                                            
title = "Slides"
url = "http://slides.mateimicu.com"
```
and it will show up like this:
image

And of course you can add multiple links:

```
[[params.static]]                                                                                                                                                                                            
title = "Slides"
url = "http://slides.mateimicu.com"
[[params.static]]                                                                                                                                                                                            
title = "Slides2"
url = "http://slides.mateimicu.com/2"
```

image

### CODE REVIEW

**Comment by ribice** [comment]
Can you document these changes in Readme? Thanks!

**Comment by mateimicu** [comment]
Added a little section with a config sample.
Would you like me to add a picture ?

**Comment by ribice** [comment]
Not needed. I'll probably edit the text a bit tomorrow, and add it to example site as well.

**Comment by russparsloe** [comment]
This seems similar to sections (#23) which uses this configuration format:
```
[params.sections]
  "/about" = "About"
  "/posts" = "Posts"
```
Can this be altered to make both options consistent in how they are configured in `config.toml`?

**Comment by ribice** [comment]
@russparsloe That would be great!

**Comment by mateimicu** [comment]
I'll make the change today :D

**Comment by ribice** [comment]
@mateimicu: Any update?

**Pull request merged**
